# Generated by Django 3.1.7 on 2021-03-31 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'owner')},
        ),
    ]
