# Generated by Django 3.1.7 on 2021-04-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api_app', '0003_auto_20210331_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
